.default_script: &default_script
  script:
    - ruby -v
    - bundle exec rubocop --config .rubocop.yml
    - bundle exec rake wwtd:local

cache:
  untracked: true
  paths:
    - .bundle/
    - vendor/bundle/

before_script:
  - 'grep -q "/debian jessie main" /etc/apt/sources.list && echo "deb http://cdn-fastly.deb.debian.org/debian/ jessie main" > /etc/apt/sources.list.d/jessie.list'
  - 'grep -q "/debian jessie main" /etc/apt/sources.list && echo "deb http://security.debian.org/ jessie/updates main" > /etc/apt/sources.list.d/jessie-updates.list'
  - 'grep -q "/debian jessie main" /etc/apt/sources.list && echo "deb http://archive.debian.org/debian jessie-backports main" > /etc/apt/sources.list.d/jessie-backports.list'
  - 'grep -q "/debian jessie main" /etc/apt/sources.list && echo "Acquire::Check-Valid-Until no;" > /etc/apt/apt.conf.d/99no-check-valid-until'
  - sed -i '/jessie.* main/d' /etc/apt/sources.list
  - 'apt-get update -y -qq && apt-get install -y -qq locales'
  - echo "en_US UTF-8" > /etc/locale.gen
  - locale-gen en_US.UTF-8
  - export LANG=en_US.UTF-8
  - export LANGUAGE=en_US:en
  - export LC_ALL=en_US.UTF-8
  - gem install bundler -v 1.16.2 --wrappers --no-document
  - 'bundle install --path vendor/bundle --jobs $(nproc) "${FLAGS[@]}"'

ruby-2.3.7:
  image: ruby:2.3.7
  <<: *default_script

ruby-2.4.4:
  image: ruby:2.4.4
  <<: *default_script

ruby-2.5.1:
  image: ruby:2.5.1
  <<: *default_script

ruby-2.6.3:
  image: ruby:2.6.3
  <<: *default_script
