inherit_from: .rubocop_todo.yml

require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.2
  DisplayCopNames: true
  Exclude:
    - 'vendor/**/*'
    - '.git/**/*'
    - 'gemfiles/**/*'

Metrics/LineLength:
  Max: 100
  IgnoredPatterns:
    - '^\s*#'
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Layout/AlignHash:
  EnforcedHashRocketStyle: table
  EnforcedColonStyle: table

RSpec/DescribeClass:
  Exclude:
    - 'spec/action_view/**/*'
