inherit_from: .rubocop_todo.yml

require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.2
  DisplayCopNames: true
  Exclude:
    - 'vendor/**/*'
    - '.git/**/*'
    - 'gemfiles/**/*'

Metrics/LineLength:
  Max: 100
  IgnoredPatterns:
    - '^\s*#'
  Exclude:
    - 'spec/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/Encoding:
  Exclude:
    - 'bemer.gemspec'