langauge: ruby

sudo: false

cache: bundler

notifications:
  email: false

rvm:
  - 2.2.0
  - 2.2
  - 2.3
  - 2.4
  - 2.5

gemfile:
  - gemfiles/3.2.gemfile
  - gemfiles/4.0.gemfile
  - gemfiles/4.1.gemfile
  - gemfiles/4.2.gemfile
  - gemfiles/5.0.gemfile
  - gemfiles/5.1.gemfile
  - gemfiles/5.2.gemfile

matrix:
  exclude:
    - rvm: 2.2.0
      gemfile: gemfiles/5.0.gemfile
    - rvm: 2.2.0
      gemfile: gemfiles/5.1.gemfile
    - rvm: 2.2.0
      gemfile: gemfiles/5.2.gemfile
